### ISSUE TITLE
Date Types

### ISSUE THREAD

**Issue by billraper** [greenfishbluefish/sims_loader#2]
Thinking about dates & timestamps…

Currently your types are restricted to various known permutations of strings.

Maybe you can add some things like:

                date_in_past
                date_in_future
                date (default, goes either direction, unbounded)
                date_in_past_N 
                date_in_future_N 
                date_N 

The “N” would be the number of YEARS for the bounding.  Perhaps offer just a couple out of the box.

For “time” data type, I would not offer a control option.  Time is just a simple random 24-hour time.

For a timestamp, I would offer only permutations that control the date range.

By doing the past, future, and either direction, you don’t have to read multiple parms.

**Comment by robkinyon** [comment]
This was released in 0.000011.
